# Generated by Django 3.1.7 on 2021-03-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='complete',
            field=models.ManyToManyField(blank=True, related_name='complete', to='tests.Tests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='create_test',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.tests'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tests',
            name='questions',
            field=models.ManyToManyField(blank=True, to='tests.Question'),
        ),
    ]
