# Generated by Django 3.1.7 on 2021-03-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20210327_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
    ]
