# Generated by Django 3.1.7 on 2021-03-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='lock_other',
        ),
    ]
