# Generated by Django 3.1.7 on 2021-03-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_choice_lock_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='visible',
        ),
    ]
